

spring.datasource.url=jdbc:postgresql://localhost:5432/foodapp
spring.datasource.username=foodapp_user
spring.datasource.password=foodapp_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

google.maps.api.key=${GOOGLE_MAPS_API_KEY}
